apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-manager-prod

resources:
- ../../base
- hpa.yaml                       # Chỉ prod có HPA
- pdb.yaml                       # Pod Disruption Budget

patches:
- target:
    kind: Deployment
    name: backend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 5
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "200m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "1000m"

- target:
    kind: ConfigMap
    name: backend-config
  patch: |-
    - op: replace
      path: /data/LOG_LEVEL
      value: warn

# Override Ingress host cho prod
- target:
    kind: Ingress
    name: task-manager
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: taskmanager.com