{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  # Pattern: tên service đơn giản (không có release name)
  # vì frontend Nginx hardcode "backend" trong proxy_pass
  name: backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "task-manager.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "task-manager.backend.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
{{- end }}
