{{- if .Values.backend.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "task-manager.backend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.backend.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.backend.externalSecret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.backend.externalSecret.dbSecretName | required "backend.externalSecret.dbSecretName is required when externalSecret.enabled=true" }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.backend.externalSecret.dbSecretName }}
        property: password
{{- end }}
