{{- if .Values.backend.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "task-manager.backend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.backend.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.backend.externalSecret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.backend.externalSecret.awsSecretName | required "backend.externalSecret.awsSecretName is required" }}
        property: JWT_SECRET
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: {{ .Values.backend.externalSecret.awsSecretName }}
        property: JWT_REFRESH_SECRET
{{- end }}
