{{- if .Values.backend.externalSecret.enabled -}}
# ClusterSecretStore cho External Secrets Operator
# Note: ClusterSecretStore là cluster-scoped → chỉ tạo 1 lần
# Khi deploy nhiều env vào cùng cluster, set externalSecret.enabled chỉ ở 1 env
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.backend.externalSecret.secretStoreName }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
{{- end }}
