{{/* Service Accounts cho 3 components: backend, frontend, postgres */}}

{{- if .Values.serviceAccounts.backend.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.backend.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "task-manager.backend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
automountServiceAccountToken: {{ .Values.serviceAccounts.backend.automountToken }}
{{- end }}

{{- if .Values.serviceAccounts.frontend.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.frontend.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "task-manager.frontend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
automountServiceAccountToken: {{ .Values.serviceAccounts.frontend.automountToken }}
{{- end }}

{{- if and .Values.postgres.enabled .Values.serviceAccounts.postgres.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.postgres.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "task-manager.postgres.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
automountServiceAccountToken: {{ .Values.serviceAccounts.postgres.automountToken }}
{{- end }}
