# platform/argocd/apps/task-manager-dev.yaml
#
# ArgoCD Application: deploy task-manager vào dev env.
# File này được quản lý bởi root App-of-Apps.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # ⚠️ ĐỔI THÀNH URL CONFIG REPO CỦA BẠN
    repoURL: https://github.com/Devop-Projects/nt548-config.git
    targetRevision: main
    path: apps/task-manager/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: task-manager-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
